TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Create and install (or just install) into <top>/db
DB += nidaq_WaveGen.template
DB += nidaq_WaveGenN.template
DB += nidaq_AI.template
DB += nidaq_AIWaveform.template
DB += nidaq_AIWaveformN.template
DB += nidaq_DIO.template
DB += nidaq_Counter.template

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

